AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with Docker to run a Streamlit app

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName
  AMIImage:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:

  StreamlitSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and Streamlit traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8501
          ToPort: 8501
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  StreamlitInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups: [!Ref StreamlitSecurityGroup]
      ImageId: !Ref AMIImage
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 30
            VolumeType: gp2
            DeleteOnTermination: true
      UserData: 
        Fn::Base64: !Sub |
          #!/bin/bash
          exec > >(tee /var/log/user-data.log | logger -t user-data -s 2>/dev/console) 2>&1
          set -e
          export DEBIAN_FRONTEND=noninteractive
          yum update -y
          yum install -y python3 python-is-python3 python3-venv curl unzip nginx docker git

          service docker start
          usermod -aG docker ec2-user

          # Create mlflow-folder and a virtual environment inside it
          mkdir -p /home/ubuntu/mlflow-folder
          cd /home/ubuntu/mlflow-folder
          python3 -m venv venv

          # Activate the virtual environment
          source venv/bin/activate

          # Upgrade pip and install required packages
          pip install --upgrade pip
          pip install virtualenv awscli boto3
          pip install --force-reinstall blinker

          echo "Installing MLflow..." | tee -a /home/ubuntu/mlflow-folder/pip-install.log
          pip install "mlflow[extras]" 2>&1 | tee -a /home/ubuntu/mlflow-folder/pip-install.log

          
          # Create working directory for MLflow artifacts
          mkdir -p /home/ubuntu/mlflow-folder/tracking

          # Start MLflow server in background with nohup
          nohup /home/ubuntu/mlflow-folder/venv/bin/mlflow server \
            --host 0.0.0.0 \
            --port 5000 \
            --default-artifact-root s3://mlflow-tracker-s3 \
            --backend-store-uri sqlite:///mlflow.db > /home/ubuntu/mlflow-folder/mlflow.log 2>&1 &

          echo "MLflow setup completed." | tee /home/ubuntu/mlflow-folder/userdata-status.txt


          echo "cd /home/ec2-user

          # If app folder already exists, pull latest changes
          if [ -d app/.git ]; then
            cd app
            git pull origin main
          else
            git clone https://github.com/Aishwarya1223/Used-Car-Price-Prediction-System app
            cd app
          fi

          # Build and run the app container
          if [ "$(docker ps -q)" ]; then
            docker stop $(docker ps -q)
          fi

          if [ "$(docker ps -aq)" ]; then
            docker rm $(docker ps -aq)
          fi

          docker build -t used-car-predict-app .
          docker run -d -p 8501:8501 used-car-predict-app
          " > /home/ec2-user/start.sh

          chmod +x /home/ec2-user/start.sh
          chown ec2-user:ec2-user /home/ec2-user/start.sh
          sudo -u ec2-user bash /home/ec2-user/start.sh

  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref StreamlitInstance

  MlflowEC2Role:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: MlflowS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement: 
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                - !Sub arn:aws:s3:::mlflow-tracker-s3
                - !Sub arn:aws:s3:::mlflow-tracker-s3/*
  MLflowInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref MlflowEC2Role]

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mlflow-tracker-s3
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
    

Outputs:
  InstancePublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt StreamlitInstance.PublicIp

  AppURL:
    Description: URL to access the Streamlit app
    Value: !Sub "http://${StreamlitInstance.PublicIp}:8501"
