AWSTemplateFormatVersion: '2010-09-09'
Description: EC2 instance with Docker to run a Streamlit app

Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair
    Type: AWS::EC2::KeyPair::KeyName
  AMIImage:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/canonical/ubuntu/server/22.04/stable/current/amd64/hvm/ebs-gp2/ami-id

Resources:
  AdminUser:
    Type: AWS::IAM::User
    Properties:
      UserName: admin-project-user
      Path: '/'

  AdminPolicyAttachment:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AdminUserPolicy
      Users:
        - !Ref AdminUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "*"
            Resource: "*"

  AdminAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref AdminUser

  StreamlitSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and Streamlit traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8501
          ToPort: 8501
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 5000
          ToPort: 5000
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  StreamlitInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups: [!Ref StreamlitSecurityGroup]
      ImageId: !Ref AMIImage
      IamInstanceProfile: !Ref MLflowInstanceProfile
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 30
            VolumeType: gp2
            DeleteOnTermination: true
      Tags:
        - Key: Name
          Value: streamlit-mlflow-server
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          exec > >(tee /var/log/user-data.log | logger -t user-data -s 2>/dev/console) 2>&1
          set -e
          export DEBIAN_FRONTEND=noninteractive

          # Update and install dependencies
          apt-get update -y
          apt-get install -y python3 python3-pip python-is-python3 python3-venv docker.io curl unzip nginx git awscli jq \
          build-essential libssl-dev libffi-dev python3-dev

          systemctl enable docker
          systemctl start docker
          sleep 5
          systemctl restart docker
          usermod -aG docker ubuntu
          
          # Create mlflow-folder and a virtual environment inside it
          mkdir -p /home/ubuntu/mlflow-folder
          chown -R ubuntu:ubuntu /home/ubuntu/mlflow-folder

          python3 -m venv /home/ubuntu/mlflow-folder/venv
          
          # Upgrade pip and install required packages
          /home/ubuntu/mlflow-folder/venv/bin/pip install --upgrade pip

          /home/ubuntu/mlflow-folder/venv/bin/pip install --force-reinstall blinker

          /home/ubuntu/mlflow-folder/venv/bin/pip install virtualenv boto3 dvc[gs,s3] mlflow[extras] \
            2>&1 | tee -a /home/ubuntu/mlflow-folder/pip-install.log


        
          SECRET_JSON=$(aws secretsmanager get-secret-value \
            --secret-id AdminUserAccessKeys \
            --region ${AWS::Region} \
            --query SecretString --output text)

          export AWS_ACCESS_KEY_ID=$(echo $SECRET_JSON | jq -r .AccessKeyId)
          export AWS_SECRET_ACCESS_KEY=$(echo $SECRET_JSON | jq -r .SecretAccessKey)

          echo "Installing MLflow..." | tee -a /home/ubuntu/mlflow-folder/pip-install.log
          
          # Create working directory for MLflow artifacts
          mkdir -p /home/ubuntu/mlflow-folder/tracking

          # Start MLflow server in background with nohup 

          nohup /home/ubuntu/mlflow-folder/venv/bin/mlflow server \
            --host 0.0.0.0 \
            --port 5000 \
            --default-artifact-root s3://mlflow-tracker-s3 \
            --backend-store-uri sqlite:///mlflow.db > /home/ubuntu/mlflow-folder/mlflow.log 2>&1 &


          echo "MLflow setup completed." | tee /home/ubuntu/mlflow-folder/userdata-status.txt
          mkdir -p /home/ubuntu/mlflow-folder/app
          if [ -d /home/ubuntu/mlflow-folder/app/.git ]; then
            git -C /home/ubuntu/mlflow-folder/app pull origin main
          else
            git clone https://github.com/Aishwarya1223/Used-Car-Price-Prediction-System /home/ubuntu/mlflow-folder/app
          fi


          chown -R ubuntu:ubuntu /home/ubuntu/mlflow-folder/app
          git config --global --add safe.directory /home/ubuntu/mlflow-folder/app

          # Pull DVC data
          /home/ubuntu/mlflow-folder/venv/bin/dvc pull

          # Build and run Streamlit app
          docker build -t used-car-predict-app /home/ubuntu/mlflow-folder/app
          docker run -d -p 8501:8501 --restart=always \
            -w /app \
            -v /home/ubuntu/mlflow-folder/app:/app \
            used-car-predict-app

          echo "Streamlit app running successfully" | tee /home/ubuntu/mlflow-folder/userdata-status.txt


  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref StreamlitInstance

  MlflowEC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: MlflowS3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::mlflow-tracker-s3
                  - !Sub arn:aws:s3:::mlflow-tracker-s3/*
        - PolicyName: SecretAccessPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref StoreAdminSecret
        - PolicyName: CFNInitAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStackResource
                Resource: "*"

  StoreAdminSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: !Sub "${AWS::StackName}-AdminUserAccessKeys"
      Description: "Access keys for admin-user"
      SecretString: !Sub |
        {
          "AccessKeyId": "${AdminAccessKey}",
          "SecretAccessKey": "${AdminAccessKey.SecretAccessKey}"
        }
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete

  MLflowInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles: [!Ref MlflowEC2Role]

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: mlflow-tracker-s3
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred

Outputs:
  InstancePublicIP:
    Description: Public IP of the EC2 instance
    Value: !GetAtt StreamlitInstance.PublicIp

  AppURL:
    Description: URL to access the Streamlit app
    Value: !Sub "http://${StreamlitInstance.PublicIp}:8501"
