name: Auto Deploy to EC2 on Model Update

on:
  workflow_run:
    workflows: ["Auto Retrain Model"]
    types:
      - completed
  workflow_dispatch: 

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > used-car-project-keypair.pem
          chmod 600 used-car-project-keypair.pem

      - name: Connect to EC2 and redeploy
        run: |
          ssh -o StrictHostKeyChecking=no -i used-car-project-keypair.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/app
            git pull origin main
            docker stop $(docker ps -q) || true
            docker rm $(docker ps -a -q) || true
            docker build -t used-car-predict-app .
            docker run -d -p 8501:8501 --name used-car-app used-car-predict-app
          EOF
