name: Auto Retrain Model

on:
  schedule:
    - cron: "0 0 * * SUN" # Every Sunday
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --no-cache-dir https://h2o-release.s3.amazonaws.com/h2o/rel-3.46.0/7/Python/h2o-3.46.0.7-py2.py3-none-any.whl

      - name: Export MySQL ENV Vars
        run: |
          echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> $GITHUB_ENV
          echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> $GITHUB_ENV
          echo "MYSQL_HOST=${{ secrets.MYSQL_HOST }}" >> $GITHUB_ENV
          echo "MYSQL_PORT=${{ secrets.MYSQL_PORT }}" >> $GITHUB_ENV
          echo "MYSQL_DB=${{ secrets.MYSQL_DB }}" >> $GITHUB_ENV

      - name: Set up MLflow tracking
        run: echo "MLFLOW_TRACKING_URI=./mlruns" >> $GITHUB_ENV

      - name: Run Training Script
        run: python train.py

      - name: Commit and Push Best Model
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add best_model/
          git diff --cached --quiet || git commit -m "Auto-retrained best model at $(date -u +'%Y-%m-%d %H:%M:%S')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
